### ISSUE TITLE
Remove usethis from Suggests?

### ISSUE THREAD

**Issue by jennybc** [luomus/finbif#1]
I will soon submit usethis v2.0.0 to CRAN.

I see that usethis is in Suggests for finbif, but I don't think the package itself actually uses usethis. I see that it's used below `data-raw/`, but that's a development dependency. I'm wondering if you might want to remove usethis from Suggests?

Selflishly, this means finbif is no longer a revdep that I need to check or that CRAN checks whenever usethis updates.

In any case, at the moment, finbif is one of the revdep failures I see, yet I don't think this has anything to do with usethis. I'm not sure what the problem is and it's seen when checking finbif against both the CRAN and dev versions of usethis.

Here's what I'm seeing if you want to take a look:

https://github.com/r-lib/usethis/blob/9bcf5b1cedb23a3f7806f6446597c2af46fc1c25/revdep/failures.md#finbif

Presumably there is some set of conditions, fulfilled by our cloud revdep check system, for which calling `get_locale()` in `.onLoad()` does not work (?). I realize this may be of no practical relevance.

**Comment by wkmor1** [comment]
Sure thing Jenny. Happy to remove usethis from Suggest. Like you say it is just used in development when building package datasets. Have removed it from the dev version of finbif now 4867696f5a9a423745a1d2380dfb3fb830d18746. Are you in a hurry for this change to go to CRAN? I am working on finbif v0.4.0 now and will hopefully be finalising it in the next few weeks or early in the new year at the latest.

Thanks for the heads up re `get_locale()` btw. Was some naive code there that was handling language codes I wasn't anticipating poorly. Should be fixed by 6e8a16ce01000836e8521e3802c2b97e72e7674c

**Comment by jennybc** [comment]
Thanks!

No, there's no urgency around this from my end. I can install and check finbif fine locally, so having it as a nominal revdep isn't hurting anything today or for the v2.0.0 release process. I just wanted to alert you to what I saw in our cloud check environment, since I had to diagnose it myself.
